export const ADD_CART_START = 'ADD_CART_START';
export const ADD_CART_FAILURE = 'ADD_CART_FAILURE';
export const GET_CART_START = 'GET_CART_START';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILURE = 'GET_CART_FAILURE';
export const COLLECT_CART_START = 'COLLECT_CART_START';
export const COLLECT_CART_SUCCESS = 'COLLECT_CART_SUCCESS';
export const COLLECT_CART_FAILURE = 'COLLECT_CART_FAILURE';